events {}

http {
    upstream onboarding { server onboarding_service:3001; }
    upstream integrations { server integrations_service:3002; }
    upstream scoring { server scoring_service:3003; }
    upstream credit { server credit_core_service:3004; }

    server {
        listen 80;

        location /api/onboarding/ { proxy_pass http://onboarding/; }
        location /api/integrations/ { proxy_pass http://integrations/; }
        location /api/scoring/ { proxy_pass http://scoring/; }
        location /api/credit/ { proxy_pass http://credit/; }
    }
}
